#spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/aiot3-team3-project?currentSchema=core
#spring.datasource.username=aiot3-team3
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#
spring.datasource.url=jdbc:postgresql://localhost:5432/insighton
spring.datasource.name=insighton
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=insighton
spring.datasource.password=insighton
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
