spring.application.name=InsightOn-core
weather.api.kma-base-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
weather.api.air-base-url=https://apis.data.go.kr/B552584/ArpltnInforInqireSvc


# JPA ??
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Hibernate ?? ?? (properties.hibernate -> spring.jpa.properties.hibernate)
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.highlight_sql=false
spring.jpa.properties.hibernate.auto_quote_keyword=true
