# dev \uD504\uB85C\uD30C\uC77C\uC5D0\uC11C\uB9CC \uB2E4\uB978 \uC124\uC815. \uACF5\uD1B5 \uC124\uC815\uC740 application.properties \uCC38\uACE0.
spring.config.import=classpath:config/dev/actuator.properties, classpath:config/dev/db.properties, classpath:config/dev/redis.properties, classpath:config/dev/redis-telemetry.properties, classpath:config/dev/rabbitmq.properties, classpath:config/dev/influxdb.properties, classpath:config/dev/weather.properties
service-url.auth=http://localhost:8000
server.port=8300

