### 전역 변수 설정
@baseUrl = http://localhost:8080
@userId = 1
@groupId = 1
@userRole = ADMIN
@inviteToken = da03414095a1

### 1. 그룹 생성
POST {{baseUrl}}/api/v1/groups/create
Content-Type: application/json
X-USER-ID: {{userId}}

{
  "name": "테스트 회사 C",
  "description": "http test 위한 테스트 회사",
  "groupRegion": "광주광역시 동구"
}

### 2. 내 그룹 정보 조회
GET {{baseUrl}}/api/v1/groups/{{groupId}}/my-group
X-USER-ID: {{userId}}

### 3. 초대받은 그룹 정보 미리보기
GET {{baseUrl}}/api/v1/groups/{{groupId}}/preview?inviteToken={{inviteToken}}
X-USER-ID: {{userId}}

### 4. 시스템 관리자용 그룹 리스트 조회
GET {{baseUrl}}/api/v1/groups/admin/group-list?page=0&size=10&sort=groupId,desc
X-USER-ID: {{userId}}
X-USER-ROLE: {{userRole}}

### 5. 초대 토큰 재발급
PUT {{baseUrl}}/api/v1/groups/{{groupId}}/invite-token/new
X-USER-ID: {{userId}}

### 6. 그룹 정보 수정
PUT {{baseUrl}}/api/v1/groups/{{groupId}}/update
Content-Type: application/json
X-USER-ID: {{userId}}

{
  "name": "테스트 회사 C 수정",
  "description": "http test 위한 테스트 회사 수정",
  "groupRegion": "광주광역시 남구"
}

### 7. 그룹 삭제
DELETE {{baseUrl}}/api/v1/groups/{{groupId}}/delete
X-USER-ID: {{userId}}