### 전역 변수 설정
@baseUrl = http://localhost:8080
@userId = 2
@groupId = 5
@locationId = 3
@widgetId = 10

### 1-3. 위젯 생성 (대시보드 저장 API를 통해 위젯 생성)
POST {{baseUrl}}/api/v1/groups/{{groupId}}/location/{{locationId}}/dashboard/save
Content-Type: application/json
X-USER-ID: {{userId}}

[
  {
    "widgetId": null,
    "x": 0,
    "y": 0,
    "w": 4,
    "h": 4,
    "widgetConfig": {
      "type": "BAR",
      "sensorEui": "DEV_LOCATION_01",
      "range": "-24h",
      "aggregateWindow": "15m",
      "fields": [
        "temperature",
        "humidity"
      ],
      "groupId": 2,
      "locationId": 1
    }
  },
  {
    "widgetId": null,
    "x": 0,
    "y": 0,
    "w": 4,
    "h": 4,
    "widgetConfig": {
      "type": "GRAPH",
      "sensorEui": "DEV_LOCATION_01",
      "range": "-24h",
      "aggregateWindow": "15m",
      "fields": [
        "temperature",
        "humidity"
      ],
      "groupId": 2,
      "locationId": 1
    }
  }
]