weather.api.kma-base-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
weather.api.kma-midterm-base-url=https://apis.data.go.kr/1360000/MidFcstInfoService
weather.api.air-base-url=https://apis.data.go.kr/B552584/ArpltnInforInqireSvc
weather.api.kma-key=${KMA_KEY}
weather.api.kma-midterm-key=${KMA_MIDTERM_KEY}
weather.api.air-key=${AIR_KEY}
